const THREAD_COLLECT_RECENT = 'THREAD_COLLECT_MOSTRECENT'; 
const THREAD_COLLECT_FIXED = 'THREAD_COLLECT_FIXED'; 
const THREAD_COLLECT_MOST_VIEW = 'THREAD_COLLECT_MOST_VIEW'; 
module.exports = {
  THREAD_COLLECT_RECENT,
  THREAD_COLLECT_MOST_VIEW,
  THREAD_COLLECT_FIXED,
};
